//
//  FloatingAnimationKit.swift
//  FloatingAnimation
//
//  Created by Proseth on 4/10/17.
//  Copyright © 2017 NANITA co .ltd. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class FloatingAnimationKit : NSObject {

    //// Drawing Methods

    public dynamic class func drawFloatingAnimation(frameWidth:CGFloat,frameHeight:CGFloat,floatingCircleWidth:CGFloat,floatingCircleHeight:CGFloat ,master: CGFloat, opacity:CGFloat, multiplierScale:CGFloat) {
        //// General Declarations
        let resizing: ResizingBehavior = .aspectFit
        let targetFrame: CGRect = CGRect(x: 0, y: 0, width: frameWidth, height: frameHeight)
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: frameWidth, height: frameHeight), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / frameWidth, y: resizedFrame.height / frameHeight)


        //// Color Declarations
        let color = UIColor(red: 0.690, green: 0.761, blue: 0.000, alpha: opacity)

        //// Variable Declarations
        let scaleX: CGFloat = master*multiplierScale
        let scaleY: CGFloat = master*multiplierScale
        let circlewidth: CGFloat = floatingCircleWidth
        let circleHeight: CGFloat = floatingCircleHeight

        //// Oval Drawing
        context.saveGState()
        context.translateBy(x: frameWidth/2 , y: frameHeight/2)
        context.scaleBy(x: scaleX, y: scaleY)

        let ovalPath = UIBezierPath(ovalIn: CGRect(x: -64, y: -64, width: circlewidth, height: circleHeight))
        color.setFill()
        ovalPath.fill()

        context.restoreGState()
        
        context.restoreGState()

    }




    @objc public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
